### ISSUE TITLE
是我参数配置错误了吗？

### ISSUE THREAD

**Issue by ChaoyueRiky** [kuilei0926/xixunyun#1]
Run cd ~/xixunyun
  cd ~/xixunyun
  python xixunyun.py
  shell: /bin/bash -e {0}
  env:
    USER: ***
    SIGN_GPS: 
    ADDRESS_NAME: 
    SCKEY: 
    pythonLocation: /opt/hostedtoolcache/Python/3.8.7/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.7/x64/lib
Traceback (most recent call last):
  File "xixunyun.py", line 8, in <module>
    password = user.split( )[1] # 密码
IndexError: list index out of range
Error: Process completed with exit code 1.

这是签到的错误

**Comment by ChaoyueRiky** [comment]
https://attach.52pojie.cn/forum/202101/28/195047v3xdrjsvww77ldwj.png
https://attach.52pojie.cn/forum/202101/28/195245nz8sre5rhy8kusss.png

**Comment by kuilei0926** [comment]
在secrets中配置而不是在Readme中配置

**Comment by ChaoyueRiky** [comment]
> 在secrets中配置而不是在Readme中配置

我配置好了
https://attach.52pojie.cn/forum/202102/28/112718eg1m24w5bsb24wwo.png
https://attach.52pojie.cn/forum/202102/28/112718eg1m24w5bsb24wwo.png
https://attach.52pojie.cn/forum/202102/28/113350pnj1fftf37f9ufg1.png
https://attach.52pojie.cn/forum/202102/28/113359g4klp7a1lf4515bp.png
微信上也能收到server酱的通知 可是还是没签到成功

**Comment by kuilei0926** [comment]
学校ID没写上

**Comment by kuilei0926** [comment]
配置没写对

**Comment by ChaoyueRiky** [comment]
> 配置没写对

方便留一下个wecha吗，我好问你一下问题，
账号
密码
学校id  这样的

**Comment by ChaoyueRiky** [comment]
> > 配置没写对
> 
> 方便留一下个wecha吗，我好问你一下问题，
> 账号
> 密码
> 学校ID这样的

什么意思？

**Comment by ChaoyueRiky** [comment]
> 配置没写对

什么意思呢？ 方便留一个VX吗
