### ISSUE TITLE
现在签到不了

### ISSUE THREAD

**Issue by Afurete233** [kuilei0926/xixunyun#2]
{'errorCode': -1, 'errorMessage': 'user code exception caught', 'stackTrace': 'Traceback (most recent call last):\n  File "/var/user/index.py", line 119, in main_handler\n    msg += \'你将会用账号\'+account+\'在\'+regeopage["regeocode"]["formatted_address"]+\'（经度：\'+longitude+\'，纬度\'+latitude+\'）以\'+remark_name+\'进行签到。\\n\'\nKeyError: \'regeocode\'', 'statusCode': 430}

**Comment by kuilei0926** [comment]
已修复
