### ISSUE TITLE
现在签到不了

### ISSUE THREAD

**Issue by zhang320786** [kuilei0926/xixunyun#4]
{'errorCode': -1, 'errorMessage': 'user code exception caught', 'stackTrace': 'Traceback (most recent call last):\n  File "/var/user/index.py", line 118, in main_handler\n    msg += \'你将会用账号\'+account+\'在\'+regeopage["regeocode"]["formatted_address"]+\'（经度：\'+longitude+\'，纬度\'+latitude+\'）以\'+remark_name+\'进行签到。\\n\\n\'\nTypeError: must be str, not list', 'statusCode': 430}

**Comment by hsuehly** [comment]
我的也报错了

{'errorCode': -1, 'errorMessage': 'Traceback (most recent call last):\n  File "/var/runtime/python3/bootstrap.py", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(".", 1)[0], func)\n  File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module\n    return load_source(name, filename, file)\n  File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source\n    module = _load(spec)\n  File "<frozen importlib._bootstrap>", line 675, in _load\n  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked\n  File "<frozen importlib._bootstrap_external>", line 674, in exec_module\n  File "<frozen importlib._bootstrap_external>", line 781, in get_code\n  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code\n  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed\n  File "/var/user/index.py", line 49\n    print("Received event: " + (event, indent = 2))\n                                              ^\nSyntaxError: invalid syntax', 'statusCode': 443}

**Comment by kuilei0926** [comment]
> 我的也报错了
> 
> {'errorCode': -1, 'errorMessage': 'Traceback (most recent call last):\n File "/var/runtime/python3/bootstrap.py", line 133, in init_handler\n func_handler = get_func_handler(file.rsplit(".", 1)[0], func)\n File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler\n mod = imp.load_module(mname, *imp.find_module(mname))\n File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module\n return load_source(name, filename, file)\n File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source\n module = _load(spec)\n File "", line 675, in _load\n File "", line 655, in _load_unlocked\n File "", line 674, in exec_module\n File "", line 781, in get_code\n File "", line 741, in source_to_code\n File ""，行205，在_call_with_frames_removed\n文件"/var/用户/索引.py"，行49\n打印（"收到的事件："+（事件，凹痕=2）\n[nSyntaxeror：无效语法'，"状态代码"：443}

已修复

**Comment by kuilei0926** [comment]
配置错误了

**Comment by XdxdGkld** [comment]
加1，同样出现了{'errorCode': -1, 'errorMessage': 'user code exception caught', 'stackTrace': 'Traceback (most recent call last):\n File "/var/user/index.py", line 118, in main_handler\n msg += '你将会用账号'+account+'在'+regeopage["regeocode"]["formatted_address"]+'（经度：'+longitude+'，纬度'+latitude+'）以'+remark_name+'进行签到。\n\n'\nTypeError: must be str, not list', 'statusCode': 430}

尝试多次重新配置，更改账号，在12号左右是没啥问题的，后面虽然也在签到成功但是签到日志中没有账号信息等，遂昨日尝试更改账号，更改后出现这条日志。顺便谢谢您的readme很详细，还想问一下您提到的手动push谷歌查的好像和想要手动启动不太一样，如果能方便解释一下就更好啦，谢谢您。
