### ISSUE TITLE
打卡失败。。。

### ISSUE THREAD

**Issue by 2594881610** [kuilei0926/xixunyun#7]
访问返回如图响应咋回事啊。
![4WUX1FH7QZQ@XGN8 X1L~_B](https://user-images.githubusercontent.com/59248523/143386336-779490bd-e208-486a-9b43-75c443649e80.png)

必须要在github上面填写参数然后用actions运行嘛。我直接把要传的参数写在代码里就会这样，用postman测试也会这样。只有用actions会成功。

**Comment by kuilei0926** [comment]
参数错误
